### ISSUE TITLE
Typescript Error at `pre` hook?

### ISSUE THREAD

**Issue by emjimadhu** [kpfromer/nestjs-typegoose#26] opened 2019-06-23 15:55 UTC
I have i am trying to implement `pre` hook. The following code works fine, but it is giving me TS lint error `potantially invalid reference access to a class field via this. of a nested function`.

```
@pre<Cat>('save', function (next) {
  this.updatedAt = new Date();
  next();
})
```

But the above code working though. It updates my updatedaAt field.

I am not sure this is related to this library or typegoose itself. But any help would be appriciated!

Thanks.

**Comment by huazai128** [comment] 2019-06-25 09:07
import * as mongooseAutoIncrement from 'mongoose-auto-increment'
@plugin(mongooseAutoIncrement.plugin, {
    model: Test.name,
    field: 'id',
    startAt: 1,
    incrementBy: 1,
})

When saving, this plugin causes the request to continue, neither error nor output

**Comment by kpfromer** [comment] 2019-07-12 01:52
Strange, I am not getting the same typescript linting message. Could you create an example repo for me to test?

**Comment by hasezoey** [comment] 2019-10-17 01:46
@emjimadhu please add more context, because currently it seems like it is an typegoose issue, not an nestjs-typegoose one

what would be good to have is an fully reproduce able code, or just the whole class the hook is on

**Comment by AlecDusheck** [comment] 2019-10-19 01:25
This message appeared for me as a warning in WebStorm. It doesn't appear to be a Typescript linting error but instead just a false-positive warning displayed in WebStorm.

This is a non-issue.

![Screenshot_1](https://user-images.githubusercontent.com/22039172/67135949-55c09500-f1e5-11e9-896b-2e24105a7a6e.png)

**Comment by hasezoey** [comment] 2019-10-19 01:29
this error dosnt happen in vscode, i think this is webstorm specific, because for the hooks the `this` is defined for hook functions

**Comment by AlecDusheck** [comment] 2019-10-19 01:32
Yeah I think something about the decorator confuses the WebStorm inspector and makes it believe that you don't have access to `this`

**Comment by JakeAi** [comment] 2020-02-02 05:21
@emjimadhu @AlecDusheck @kpfromer  I use webstorm and this is what I use
```TS
@pre<User>('save', async function(this: DocumentType<User>, next) {})
```

**Comment by kpfromer** [comment] 2020-03-01 21:55
Closing this issue because it has been resolved.

**Closed by kpfromer** 2020-03-01 21:55 UTC
